=== laurentmor/INF4375/exemples/XML/document-schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="discography">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="artist" type="xs:string" />
        <xs:element minOccurs="0" maxOccurs="unbounded" name="release">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string" />
              <xs:element name="artist" type="xs:string" />
              <xs:element name="year" type="xs:unsignedShort" />
              <xs:element name="label" type="xs:string" />
            </xs:sequence>
            <xs:attribute name="type" type="xs:string" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== laurentmor/INF4375/exemples/XML/document-structurel.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>

<discography xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="document-schema.xsd">
	<artist>Jacques Berger</artist>
	<release type="demo">
		<name>TristeCiel</name>
		<artist>TristeCiel</artist>
		<year>2006</year>
		<label>Independant</label>
	</release>
	<release type="demo">
		<name>Untitled</name>
		<artist>Curism</artist>
		<year>2009</year>
		<label>Independant</label>
	</release>
	<release type="album">
		<name>Rouge</name>
		<artist>ChimÃ¨res</artist>
		<year>2010</year>
		<label>Independant</label>
	</release>
	<release type="album">
		<name>Under The Fall</name>
		<artist>Curism</artist>
		<year>2011</year>
		<label>Independant</label>
	</release>
</discography>
